name: jupysql-plugin-test
channels:
    - conda-forge
dependencies:
    - python=3.11
    - nodejs=16
    - jupyterlab<4 # this will install jlpm
    - pip
    - pip:
        - build
        - twine
        - hatch
    - yarn <2
    - ipywidgets >=8
    - traitlets >=4.3.0
    - traittypes >=0.0.6
    - numpy >=1.10.4,<2.0.0
    - pandas >=1.0.0,<2.0.0
    - bqscales  >=0.3.1
    - scipy
    - jupyter-packaging
    - pytest
    - nbval
    - pytest-cov
    - selenium
    - flake8
    - nose
    - codespell
